apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-config
  labels:
    type: local  
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/app-config"


      # kubernetes.io --> "pod with pvc"
