apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-volume
  labels:
    type: volume
spec:
  storageClassName: standard 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  containers:
    - name: web
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: w-vol
  volumes:
    - name: w-vol
      persistentVolumeClaim:
        claimName: pv-volume
