9 Schedule a pod as follow:

Name: nginx-kusc00401
Image: nginx
Node selector: disk=spinning

Answer: 
  1. kubectl get nodes --show-labels | grep disk=spinning
  2. kubectl run nginx –image=nginx –dry-run=client -o yaml > 9.yaml
 or #google  "nodeselector" "assign pods to nodes"

apiVersion: v1
kind: Pod
metadata:
  name: nginx-kusc00401
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  nodeSelector: 
    disk: spinning

      kubectl get pods -o wide
      kubectl describe pod nginx-kusc00401 | grep disk=

